REPLACEMENTS = {
    "doc": "Docs",
    "test": "Tests",
    "unittests": "Tests",
    "unit tests": "Tests",
    "cc": "CommonClient",
    "bhc": "BizHawkClient",
    "fill": "Core",
    "generate": "Core",
    "generator": "Core",
    "moduleupdate": "Core",
    "customserver": "WebHost",
    "optionscreator": "Options Creator",
    "optioncreator": "Options Creator",
    "option creator": "Options Creator",
    "rulebuilder": "Rule Builder",
    "build apworlds": "APWorld Builder",

    "ahit": "A Hat in Time",
    "alttp": "A Link to the Past",
    "lttp": "A Link to the Past",
    "cv64": "Castlevania 64",
    "cvcotm": "Castlevania - Circle of the Moon",
    "celeste open world": "Celeste (Open World)",
    "civ6": "Civilization 6",
    "ds3": "Dark Souls 3",
    "ff1": "Final Fantasy",
    "ffmq": "Final Fantasy Mystic Quest",
    "hk": "Hollow Knight",
    "jak1": "Jak and Daxter",
    "kh1": "Kingdom Hearts 1",
    "kh2": "Kingdom Hearts 2",
    "ladx": "Link's Awakening DX",
    "lufia2": "Lufia 2: Ancient Cave",
    "lufia2ac": "Lufia 2: Ancient Cave",
    "mlss": "Mario & Luigi: Superstar Saga",
    "mm2": "Mega Man 2",
    "mm3": "Mega Man 3",
    "mmbn3": "MegaMan Battle Network 3",
    "oot": "Ocarina of Time",
    "osrs": "Old School Runescape",
    "pokemon rb": "Pokemon Red/Blue",
    "pokémon rb": "Pokemon Red/Blue",
    "ror2": "Risk of Rain 2",
    "sa2b": "Sonic Adventure 2: Battle",
    "sc2": "Starcraft 2",
    "sdv": "Stardew Valley",
    "sm": "Super Metroid",
    "sm64": "Super Mario 64",
    "sm64ex": "Super Mario 64",
    "sml2": "Super Mario Land 2",
    "smw": "Super Mario World",
    "legend of zelda": "The Legend of Zelda",
    "tloz": "The Legend of Zelda",
    "zelda1": "The Legend of Zelda",
    "messenger": "The Messenger",
    "tww": "The Wind Waker",
    "wind waker": "The Wind Waker",
    "witness": "The Witness",
    "v6": "VVVVVV",
    "yi": "Yoshi's Island",
    "yugioh": "Yu-Gi-Oh! 2006",
}

CATEGORIES_THAT_GO_AT_THE_TOP = [
    "core",
    "multiserver",
    "webhost",
    "launcher",
    "commonclient",
    "bizhawkclient",
    "sniclient",
    "options",
    "settings",
    "options creator",
    "rule builder",
    "ci",
    "tests",
    "docs",
    "apworld builder",
    "kvui",
    "kivy",
    "ger",
    "setup",
    "docker",
    "pycharm",
]


def clean_category(category: str) -> str:
    category = REPLACEMENTS.get(category.lower(), category)
    if category.endswith(".py"):
        category = category[:-3]
    return category
